compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0004
    level: discard
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"
