version: 2.1

commands:
  build:
    steps:
      - run: node --version && yarn --version
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable --frozen-lockfile
      - run: yarn test
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  node-10:
    docker:
      - image: node:10
    steps:
      - build
  node-12:
    docker:
      - image: node:12
    steps:
      - build
  node-13:
    docker:
      - image: node:13
    steps:
      - build
  node-14:
    docker:
      - image: node:14
    steps:
      - build

workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-10
      - node-12
      - node-13
      - node-14
