version: 2.1

commands:
  build:
    steps:
      - run: node --version && npm --version
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-cache
      - run: npm install
      - run: npm test
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - "~/.npm/"

jobs:
  node-10:
    docker:
      - image: node:10
    steps:
      - build
  node-12:
    docker:
      - image: node:12
    steps:
      - build
  node-13:
    docker:
      - image: node:13
    steps:
      - build
  node-14:
    docker:
      - image: node:14
    steps:
      - build

workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-10
      - node-12
      - node-13
      - node-14
