version: 2.1

commands:
  build:
    steps:
      - checkout
      - run: corepack enable && corepack prepare --activate
      - run: node --version && yarn --version
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install --immutable
      - run: yarn test
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  node-18:
    docker:
      - image: node:18
    steps:
      - build
  node-20:
    docker:
      - image: node:18
    steps:
      - build

workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-18
      - node-20
